### ISSUE TITLE
Add support for Juggluco internal web-server upload direcly over wifi

### ISSUE THREAD

**Issue by lostboy86** [ktomy/nightscout-clock#1]
https://www.juggluco.nl/Juggluco/webserver

This function explained upload data from Juggluco to a compatible devices nightscout.

For example, works for M5Stack, M5Stick-C Plus, and many other devices.

In M5Stack i can write this  : http://45.67.40.94:6996/sgv.json for source, it provide this code : 

`[
    {
        "_id": "XX0F27H67CV#12758",
        "device": "Juggluco",
        "dateString": "2023-09-26T10:15:44.000+02:00",
        "sysTime": "2023-09-26T10:15:44.000+02:00",
        "date": 1695716144000,
        "sgv": 118,
        "delta": -4.1,
        "direction": "Flat",
        "noise": 1,
        "filtered": 118000,
        "unfiltered": 118000,
        "rssi": 100,
        "type": "sgv",
        "units_hint": "mgdl"
    },
    {
        "_id": "XX0F27H67CV#12753",
        "device": "Juggluco",
        "dateString": "2023-09-26T10:10:45.000+02:00",
        "sysTime": "2023-09-26T10:10:45.000+02:00",
        "date": 1695715845000,
        "sgv": 129,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 129000,
        "unfiltered": 129000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12748",
        "device": "Juggluco",
        "dateString": "2023-09-26T10:05:44.000+02:00",
        "sysTime": "2023-09-26T10:05:44.000+02:00",
        "date": 1695715544000,
        "sgv": 138,
        "delta": -0.4,
        "direction": "Flat",
        "noise": 1,
        "filtered": 138000,
        "unfiltered": 138000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12743",
        "device": "Juggluco",
        "dateString": "2023-09-26T10:00:44.000+02:00",
        "sysTime": "2023-09-26T10:00:44.000+02:00",
        "date": 1695715244000,
        "sgv": 136,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 136000,
        "unfiltered": 136000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12738",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:55:44.000+02:00",
        "sysTime": "2023-09-26T09:55:44.000+02:00",
        "date": 1695714944000,
        "sgv": 135,
        "delta": -1.7,
        "direction": "Flat",
        "noise": 1,
        "filtered": 135000,
        "unfiltered": 135000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12733",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:50:44.000+02:00",
        "sysTime": "2023-09-26T09:50:44.000+02:00",
        "date": 1695714644000,
        "sgv": 141,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 141000,
        "unfiltered": 141000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12728",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:45:44.000+02:00",
        "sysTime": "2023-09-26T09:45:44.000+02:00",
        "date": 1695714344000,
        "sgv": 145,
        "delta": -0.15,
        "direction": "Flat",
        "noise": 1,
        "filtered": 145000,
        "unfiltered": 145000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12723",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:40:45.000+02:00",
        "sysTime": "2023-09-26T09:40:45.000+02:00",
        "date": 1695714045000,
        "sgv": 145,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 145000,
        "unfiltered": 145000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12718",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:35:44.000+02:00",
        "sysTime": "2023-09-26T09:35:44.000+02:00",
        "date": 1695713744000,
        "sgv": 135,
        "delta": -3.65,
        "direction": "Flat",
        "noise": 1,
        "filtered": 135000,
        "unfiltered": 135000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12713",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:30:45.000+02:00",
        "sysTime": "2023-09-26T09:30:45.000+02:00",
        "date": 1695713445000,
        "sgv": 152,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 152000,
        "unfiltered": 152000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12708",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:25:44.000+02:00",
        "sysTime": "2023-09-26T09:25:44.000+02:00",
        "date": 1695713144000,
        "sgv": 155,
        "delta": 0.85,
        "direction": "Flat",
        "noise": 1,
        "filtered": 155000,
        "unfiltered": 155000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12703",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:20:45.000+02:00",
        "sysTime": "2023-09-26T09:20:45.000+02:00",
        "date": 1695712845000,
        "sgv": 151,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 151000,
        "unfiltered": 151000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12698",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:15:48.000+02:00",
        "sysTime": "2023-09-26T09:15:48.000+02:00",
        "date": 1695712548000,
        "sgv": 151,
        "delta": 0.25,
        "direction": "Flat",
        "noise": 1,
        "filtered": 151000,
        "unfiltered": 151000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12693",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:10:45.000+02:00",
        "sysTime": "2023-09-26T09:10:45.000+02:00",
        "date": 1695712245000,
        "sgv": 149,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 149000,
        "unfiltered": 149000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12688",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:05:44.000+02:00",
        "sysTime": "2023-09-26T09:05:44.000+02:00",
        "date": 1695711944000,
        "sgv": 150,
        "delta": 0.05,
        "direction": "Flat",
        "noise": 1,
        "filtered": 150000,
        "unfiltered": 150000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12683",
        "device": "Juggluco",
        "dateString": "2023-09-26T09:00:44.000+02:00",
        "sysTime": "2023-09-26T09:00:44.000+02:00",
        "date": 1695711644000,
        "sgv": 149,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 149000,
        "unfiltered": 149000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12678",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:55:44.000+02:00",
        "sysTime": "2023-09-26T08:55:44.000+02:00",
        "date": 1695711344000,
        "sgv": 151,
        "delta": 0.2,
        "direction": "Flat",
        "noise": 1,
        "filtered": 151000,
        "unfiltered": 151000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12673",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:50:46.000+02:00",
        "sysTime": "2023-09-26T08:50:46.000+02:00",
        "date": 1695711046000,
        "sgv": 152,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 152000,
        "unfiltered": 152000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12668",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:45:44.000+02:00",
        "sysTime": "2023-09-26T08:45:44.000+02:00",
        "date": 1695710744000,
        "sgv": 152,
        "delta": 0.8,
        "direction": "Flat",
        "noise": 1,
        "filtered": 152000,
        "unfiltered": 152000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12663",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:40:45.000+02:00",
        "sysTime": "2023-09-26T08:40:45.000+02:00",
        "date": 1695710445000,
        "sgv": 151,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 151000,
        "unfiltered": 151000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12658",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:35:44.000+02:00",
        "sysTime": "2023-09-26T08:35:44.000+02:00",
        "date": 1695710144000,
        "sgv": 149,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 149000,
        "unfiltered": 149000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12653",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:30:44.000+02:00",
        "sysTime": "2023-09-26T08:30:44.000+02:00",
        "date": 1695709844000,
        "sgv": 148,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 148000,
        "unfiltered": 148000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12648",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:25:48.000+02:00",
        "sysTime": "2023-09-26T08:25:48.000+02:00",
        "date": 1695709548000,
        "sgv": 146,
        "delta": -0.5,
        "direction": "Flat",
        "noise": 1,
        "filtered": 146000,
        "unfiltered": 146000,
        "rssi": 100,
        "type": "sgv"
    },
    {
        "_id": "XX0F27H67CV#12643",
        "device": "Juggluco",
        "dateString": "2023-09-26T08:20:44.000+02:00",
        "sysTime": "2023-09-26T08:20:44.000+02:00",
        "date": 1695709244000,
        "sgv": 144,
        "delta": 0,
        "direction": "",
        "noise": 1,
        "filtered": 144000,
        "unfiltered": 144000,
        "rssi": 100,
        "type": "sgv"
    }
`]``

M5Stack shows the value of blood glucose, without nightscout, directly offline through wifi.

Also Juggluco for my phone, take source data from CGM Libre 3, every one minutes, from bluetooth sensor.

**Comment by ktomy** [comment]
https://github.com/ktomy/nightscout-clock/commit/6094185167a77c3bde1eedfe4a3e2a8b91e6710d
The data is read from `http://<host>:<port>/api/v1/entries/sgv?count=<records>`

**Comment by ktomy** [comment]
Resolved, merged

**Comment by lostboy86** [comment]
Great , very good

Thank you for the hard work

Il dom 1 ott 2023, 22:27 Alin Artiom Kenibasov ***@***.***>
ha scritto:
