### ISSUE TITLE
Possibility to use with custom (AWTRIX) device

### ISSUE THREAD

**Issue by alphazero123** [ktomy/nightscout-clock#12]
When flashing this on a custom build 8x32 Led device (awtrix) the display pixels are not displayed properly.
On AWTRIX we use dev.json with 
{
  "matrix": 2
}

to fix the issue. Is there a way we could use nightscout clock with custom build 8x32 devices? Any help would be very appreciated

**Comment by ktomy** [comment]
I don't have the custom device thus I can't test. But I suppose that the only change needed for the solution to work would be to change https://github.com/ktomy/nightscout-clock/blob/main/src/DisplayManager.cpp#L25 and/or https://github.com/ktomy/nightscout-clock/blob/main/src/DisplayManager.cpp#L30
Besides that the firmware uses illumination sensor and could have some minor issues on the hardware not having the sensor (while it still should work if brightness is not set to "auto"

**Comment by alphazero123** [comment]
could you guide me please what changes would be needed to that line?

**Comment by ktomy** [comment]
Hmm, changing https://github.com/ktomy/nightscout-clock/blob/main/src/DisplayManager.cpp#L71 from 0 to 2 should fix it. Please  let me know if it worked

**Comment by alphazero123** [comment]
![PXL_20241020_144940631](https://github.com/user-attachments/assets/7a383f2c-f483-4195-8b33-8ee72e2c1130)

**Comment by ktomy** [comment]
Happy it helped
