### ISSUE TITLE
Since last version i can't modify this item ?

### ISSUE THREAD

**Issue by Cheun1** [ktomy/nightscout-clock#14]
Hello.

Since last version , i can't change values on this item .

Thank you .

![image](https://github.com/user-attachments/assets/8e1df95b-6b47-4cd5-833d-648d9fa80f3d)

**Comment by ktomy** [comment]
Alarms are not yet ready for production testing (and they were not ready in prievious builds too).

**Comment by Cheun1** [comment]
Oups...Sorry 
Test sounds works .....
