### ISSUE TITLE
dexcom share freeze after couple of hours

### ISSUE THREAD

**Issue by alphazero123** [ktomy/nightscout-clock#15]
Dexcom share on ulanzi freezes after couple of hours. I have clock and sugar running side by side. After couple of hours Dexcom share always freezes, clock runs fine. After a restart it works fine again for a couple of hours. I noticed when no new data update on dexcom happens the device is also not reachable anymore by ip web interface. When i hard reset device i saw a error: INVALID DEXCOM RESPONSE: NO MEMORY

**Comment by ktomy** [comment]
I will try to reproduce

**Comment by ktomy** [comment]
Fixed in v0.13
