### ISSUE TITLE
Valid SSID fails validation check

### ISSUE THREAD

**Issue by phoneyaccount** [ktomy/nightscout-clock#16]
**Describe the bug**
Valid SSID fails validation check and will not allow install to proceed if it is a singular letter. "X" or "A" for example.

**To Reproduce**
1. Have a SSID named "A"
2. Validation error during install

**Expected behavior**
Should not fail validation check for a singular letter SSID which is a valid SSID

**Screenshots / photos**
If applicable, add screenshots or clock photos to help explain your problem.

**Device information:**
- Hardware [e.g. Ulanzi TC001]
- Firmware version [e.g. v0.13]

**Additional context**

**Comment by ktomy** [comment]
Fixed in https://github.com/ktomy/nightscout-clock/commit/c60e2fcd42a7ac1e56a3ff7623569592e9ac1ab7 please update. I did not increase the version as I am still working on a good changelog mechanism, so just reinstall the firmware from the website.
