### ISSUE TITLE
Add support to one-minutes value

### ISSUE THREAD

**Issue by lostboy86** [ktomy/nightscout-clock#2]
Juggluco and other apps push every one minutes the value on Nightscout with L3 sensor, because L3 sensor read every 60 secs the blood sugar.

Can you add the support of this function in the gui?

Thanks

**Comment by ktomy** [comment]
Update mechanism polls the values from Nightscout-like API every 60 seconds. The ingterval can be changed [here](https://github.com/ktomy/nightscout-clock/blob/main/src/NightscoutManager.cpp#L36). In the future there will be "smart polling" where the firmware will detect the optimal polling moment and interval
