### ISSUE TITLE
Screen brightness dim implementation

### ISSUE THREAD

**Issue by lostboy86** [ktomy/nightscout-clock#3]
Ulanzi says 5hrs autonomous battery.

Can you add a gui for night mode, or for simple mode, support for the button to increase or decreas the brightness of the display?

Thanks in advance

**Comment by ktomy** [comment]
Done in [this ](https://github.com/ktomy/nightscout-clock/commit/a7f1a17705fb362c992993919e62254ac2d595f6)commit. For now the brightness level cannot be adjusted directly from the clock. Direct adjustment will be implemented after the clock menu implementation (i.e. around January)
