### ISSUE TITLE
Add support for Gluroo NS service

### ISSUE THREAD

**Issue by lostboy86** [ktomy/nightscout-clock#4]
Gluroo create an automatically Nightscout website without doing anything for the users, except link the app with follower-mode to the sensor companion app.

Many simple users use this function without knowledge about setup an nightscout website, can you add a support?

Thanks

**Comment by ktomy** [comment]
Done in [this ](https://github.com/ktomy/nightscout-clock/commit/faf76a7b7b31cc7ad3c6cc1a732153f94ee0e8ae)commit
