### ISSUE TITLE
MQTT Support

### ISSUE THREAD

**Issue by alfureu** [ktomy/nightscout-clock#8]
Did not test this firmware yet, but noticed you mentioned that this project is heavily based on the [AWTRIX Light](https://github.com/Blueforcer/awtrix-light) project. 

I was wondering whether it would not be easier to develop a flow for Awtrix Light directly. But in any case, as I would love to shop multiple other values on my LCD, are you planning to support MQTT for home automation?

**Comment by ktomy** [comment]
Hi, there is an integration for Home Assistant to read Nightscout value and it is possible to send these readings to the clock having AWTRIX-Light firmware out of the box.
The idea of this firmware is to have a stand-alone clock, making it available not only to the Home Assistant users, but just to everyone who uses Nightscout or even just Dexcom
